import express from 'express';
import {pool} from '../config/db.js';
import {auth,admin} from '../middleware/auth.js';
const router=express.Router();
router.post('/',auth,async(req,res)=>{const{items,shipping}=req.body;if(!items?.length)return res.status(400).json({message:'Cart is empty'});const conn=await pool.getConnection();try{await conn.beginTransaction();let total=0;const normalized=[];for(const i of items){const[r]=await conn.query('SELECT * FROM products WHERE id=? FOR UPDATE',[i.id]);if(!r.length)throw Error('Product not found');if(r[0].stock<i.quantity)throw Error(`${r[0].name} is out of stock`);total+=Number(r[0].price)*i.quantity;normalized.push({p:r[0],q:i.quantity})}const[r]=await conn.query('INSERT INTO orders(user_id,total,shipping_name,shipping_address,shipping_city,shipping_phone) VALUES(?,?,?,?,?,?)',[req.user.id,total,shipping.name,shipping.address,shipping.city,shipping.phone]);for(const x of normalized){await conn.query('INSERT INTO order_items(order_id,product_id,quantity,price) VALUES(?,?,?,?)',[r.insertId,x.p.id,x.q,x.p.price]);await conn.query('UPDATE products SET stock=stock-? WHERE id=?',[x.q,x.p.id])}await conn.commit();res.status(201).json({orderId:r.insertId,total});}catch(e){await conn.rollback();res.status(400).json({message:e.message||'Checkout failed'})}finally{conn.release()}});
router.get('/mine',auth,async(req,res)=>{const[rows]=await pool.query(`SELECT o.*, GROUP_CONCAT(CONCAT(p.name,' x',oi.quantity) SEPARATOR ', ') items FROM orders o JOIN order_items oi ON o.id=oi.order_id JOIN products p ON p.id=oi.product_id WHERE o.user_id=? GROUP BY o.id ORDER BY o.created_at DESC`,[req.user.id]);res.json(rows)});
router.get('/',auth,admin,async(req,res)=>{const[rows]=await pool.query(`SELECT o.*,u.name user_name,u.email FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC`);res.json(rows)});
router.patch('/:id/status',auth,admin,async(req,res)=>{await pool.query('UPDATE orders SET status=? WHERE id=?',[req.body.status,req.params.id]);res.json({message:'Status updated'})});
export default router;
